Pull request for Members branch
Datagirlcmr/Members-Only pull request #1
Opened 2020-01-15 22:38 UTC by Datagirlcmr

2020-01-15 23:21 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

#### PostsController `create` action:

* [ ] it makes sure that the user_id for post is the one from the signed_in user ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_create_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)).

* [ ] You should also use the `post_params` private method.

#### UsersController`create` action

* [ ] it has a create action. Must use `user_params` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_up_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))

* [ ] There should be NO application logic in the views nor helpers (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers, check [this article](http://codefol.io/posts/Where-Do-I-Put-My-Code) for reference.

**[OPTIONAL]:** Update the routes and add a `root` route so the landing page would be the login view for example instead of the new rails app page.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2020-01-15 23:21 UTC, Redvanisation commented on app/controllers/posts_controller.rb
> +    @post = Post.new()
Remove the parenthesis it's `Post.new`

2020-01-15 23:21 UTC, Redvanisation commented on app/controllers/posts_controller.rb
> +    post = Post.new(title: params[:post][:title], body: params[:post][:body], user_id: current_user.id)
You could improve this by creating the **private** `post_params` method, and changing this line after that to be
`@post = current_user.posts.build(post_params)`

2020-01-15 23:21 UTC, Redvanisation commented on app/helpers/application_helper.rb
> +  end
There should be no application logic in the views, you already implemented those methods in the `ApplicationController`

2020-01-16 16:32 UTC, maelfosso requested changes
# Congratulations :clap: 

You did it :smile: :+1: 
Good luck with the next step.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2020-01-16 18:10 UTC, merged